meta_product_name: "Stable Manager"
meta_title: "Stable Manager - Application des tâches quotidiennes en écurie"
meta_description: "Une application vous permettant de lister toutes vos tâches quotidiennes suite à l'enregistrement de tous les chevaux dans votre écurie !"
meta_image: "horse_meta.jpg"                       # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"
